### ISSUE TITLE
Adapt project to "project template" best practises

### ISSUE THREAD

**Issue by antgamdia** [isa-group/governify-cli#2]

**Comment by raffrearaUS** [comment]
Adapted in commit isa-group/governify-cli/commit/64fa29a86cda1ecee778ed9b21afe8ebca3992fc

**Comment by antgamdia** [comment]
Please, check gruntfile.js is fully updated. You should change some params concerning docker image name and github repo name.
Please also be aware if the difference between isagroup (in Docker) and isa-group (in github).
Package.json should also be carefully reviewed.

I have not reviewed all the commit, I only wanted to be sure about the changes needed.

**Comment by raffrearaUS** [comment]
The gruntfile.js has been corrected, and the banners are now updated.
